info:
  title: goezswag api
  version: 1.0.0-beta
  description: goezswag is a easy swagger
openapi: 3.0.0
paths:
  /v1/dummy/route:
    get:
      summary: create a dummy route
      tags:
      - list
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountHolder'
        "400":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Paymentz'
        "500":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyDummyModelResponse'
    post:
      summary: create a dummy route
      tags:
      - create
      - cardsonfile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MyDummyModel'
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyDummyModelResponse'
        "400":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyDummyModelResponse'
components:
  schemas:
    AccountHolder:
      properties:
        bankaccount:
          $ref: '#/components/schemas/BankAc'
        name:
          type: string
    BankAc:
      properties:
        destination:
          type: boolean
    IncomingTransferRequest:
      properties:
        longitude:
          type: number
        metadata:
          type: object
        payment_details:
          $ref: '#/components/schemas/Paymentz'
        source_holder:
          $ref: '#/components/schemas/AccountHolder'
    MyDummyModel:
      properties:
        aeho:
          description: this is a composite value
          $ref: '#/components/schemas/NestedVal'
        aeho_arrat:
          type: array
          items:
            $ref: '#/components/schemas/NestedVal'
        field_four:
          type: string
          description: field is the number four
        field_one:
          type: string
          description: field is the number one
        inc_request:
          $ref: '#/components/schemas/IncomingTransferRequest'
    MyDummyModelResponse:
      properties:
        amount:
          type: integer
        amount_double:
          type: number
          description: field double is of course doubl
      example:
        amount_double: 53.21
    NestedVal:
      properties:
        field_x:
          type: string
          description: field x is the best
        field_y:
          type: integer
          description: field y is integer
      example:
        field_x: best
        field_y: -42
    Paymentz:
      properties:
        type:
          type: string
